stages:
    - build

cache:
    paths:
        - node_modules/

deploy:
    stage: build
    image: docker:20.10.10
    only:
        - main
    services:
        - docker:20.10.10-dind
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ''
        DOCKER_DRIVER: overlay2

    before_script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    script:
        - docker build -t tiktok-ui:latest .
        - docker tag tiktok-ui taipham147/tiktok-ui:latest
        - docker push taipham147/tiktok-ui:latest
        - apk add rsync && apk add openssh
        - mkdir -p ~/.ssh
        - ssh-keyscan -H 52.220.39.194  >> ~/.ssh/known_hosts
        - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh ubuntu@52.220.39.194 "docker pull taipham147/tiktok-ui:latest"
